violaberg/memo-bubble

src/App.module.css
src/components/CapsuleBubble.jsx
src/styles/Button.module.css
src/styles/Capsule.module.css
src/styles/NavBar.module.css
src/styles/SignInUpForm.module.css

- Update primary and secondary colors in CSS for a refreshed look.
- Modify text colors to enhance readability and accessibility.
- Adjust background colors to improve contrast and visual appeal.

style: Update color scheme for improved UI

---

src/App.module.css
src/pages/auth/SignInForm.jsx
src/styles/Button.module.css
src/styles/Capsule.module.css
src/styles/NavBar.module.css
src/styles/SignInUpForm.module.css

3 custom button for light theme

Custom buttons

---

src/App.js

- Integrate cookie handling in App.js
- Implement necessary dependencies and configuration for cookie management
- Ensure user preferences and session data are stored using cookies2

feat: Add cookies support in App.js

---

package-lock.json
package.json
src/App.js
src/components/MoreDropDown.js
src/pages/contact/ContactForm.jsx
src/pages/contact/ContactPage.jsx
src/pages/legal/FAQ.jsx
src/pages/legal/PrivacyPolicy.jsx
src/pages/legal/Terms.jsx
src/styles/ContactForm.module.css
src/styles/MoreDropdown.module.css
src/styles/ServicesPages.module.css

- Install missing dependencies
- Correct import paths for ContactMessagesList, react-cookie-consent, and react-helmet-async
- Fix missing import for react-phone-number-input and associated CSS
- Resolve issues with react-phone-number-input getCountries function

fix: resolve import and variable errors in components

---

src/components/NavBar.jsx
src/contexts/CurrentUserContext.js
src/utils/utils.js

- Add Button.module.css import to NavBar.jsx
- Remove unused useState import from NavBar.jsx
- Update removeTokenTimstamp to removeTokenTimestamp in NavBar.jsx
- Update removeTokenTimstamp to removeTokenTimestamp in CurrentUserContext.js
- Update removeTokenTimstamp to removeTokenTimestamp in utils.js

chore: Update NavBar component and utils

---

src/App.module.css
src/components/Footer.jsx
src/components/footer/DeveloperDetails.jsx
src/components/footer/InfoLinks.jsx
src/components/footer/LegalLinks.jsx
src/styles/Footer.module.css
src/styles/NavBar.module.css

- Update footer styling for improved layout and design
- Add a patterned background to the footer
- Move footer component files into the 'components' folder
- Update import paths to reflect new component locations

Update footer styling, add pattern background, and reorganize component files

---

src/components/CapsuleBubble.jsx
src/styles/Capsule.module.css
src/styles/Footer.module.css

- Apply polaroid style CSS to capsule images for a nostalgic look
- Implement film strip style CSS to videos for a classic cinema effect
- Update related components and styles to enhance visual presentation
- Ensure responsive design

style: Add polaroid style to capsule images and film strip style to videos

---

src/pages/Home.jsx
src/pages/capsules/CapsuleCreateForm.jsx
src/styles/Home.module.css

- Add a new section about memories to the Home page.
- Update the styling for the new section to ensure visual consistency and appeal.
- Center content and adjust image size in the Home page for better presentation.

feat: Add memories section to home page and update styling

---

src/App.js
src/components/footer/InfoLinks.jsx
src/pages/About.jsx
src/styles/About.module.css
src/styles/Footer.module.css

- Create About.jsx component with information about the project's inception and purpose.
- Add route for About page in App.js.
- Style the About page for better presentation.
- Note: More description needed in About page

feat: Add About page with project description and update footer styling

---

package-lock.json
package.json
src/components/Footer.jsx
src/components/NavBar.jsx
src/styles/Footer.module.css
src/styles/Home.module.css
src/styles/NavBar.module.css

- Install necessary FontAwesome dependencies.
- Import FontAwesome icons in NavBar component.
- Add icons to the navigation links for Home, About, Capsules, Add Capsule, Sign in, Sign up, and Sign out.
- Update the styling of NavBar for a better user experience.

feat: Add FontAwesome icons to NavBar and update styling, add margin to footer

---

src/components/Asset.jsx
src/pages/capsules/Bubbles.jsx
src/pages/capsules/CapsuleCreateForm.jsx
src/pages/capsules/CapsulesPage.jsx

- Modify the Asset component in `Asset.jsx` to include the `animation` and `variant` props.
- Update the `Spinner` component to use the `animation` and `variant` props.
- Update the `message` paragraph element to use single quotes for the class name.
- Add the `animation` and `variant` props to the `Asset` component in `Bubbles.jsx`.
- Add a conditional rendering for the `Asset` component in `Bubbles.jsx` based on the `hasLoaded` prop.
- Add a loading spinner with the message "Loading..." when `hasLoaded` is false.
- Update the `CapsulesPage` component in `CapsulesPage.jsx` to pass the `hasLoaded` prop to the `Bubbles` component.
```

chore: Update Asset component to include animation and variant props

---

src/pages/capsules/CapsuleCreateForm.jsx

- Commented out code to test gemini 
- Add function to restrict 15 requests per minute (if page refresh counter starts over)

Add gemini model to CapsuleCreateForm component

---

src/pages/capsules/CapsuleCreateForm.jsx

- Add placeholder for gemini results for testing

Update Gemini model to CapsuleCreateForm component

---

src/pages/capsules/CapsuleCreateForm.jsx

- Add multipart upload functionality for handling large image and video files.
- Update form submission to handle multipart upload metadata.

feat: Implement multipart upload for large files in CapsuleCreateForm

---

src/App.module.css
src/pages/capsules/CapsuleCreateForm.jsx
src/styles/Button.module.css
src/styles/CapsuleCreateForm.module.css

- Enhance the layout and design of the Capsule form for better user experience

Improve styling for Capsule Form

---

src/App.js

- Footer will not be rendered in capsules and capsules/create urls to improve UX

Update to condiotional render the footer

---

src/components/Avatar.jsx
src/components/NavBar.jsx

- Modify the Avatar component to handle the case when the src value is null, displaying a placeholder image instead.

chore: Update Avatar component to handle null src value

---

src/pages/capsules/Bubbles.jsx
src/pages/capsules/CapsulesPage.jsx
src/styles/Bubbles.module.css
src/styles/Button.module.css
src/styles/Capsule.module.css

- Create bubble containers with circular design and animation
- Implement Flexbox for centering bubbles within their container
- Replace carousel with single image display inside each bubble
- Add slightly darker outer shadow to bubbles for better visual effect
- Ensure responsive design for bubbles on smaller screens
- Apply CSS styles for bubble shapes, images, and text alignment
- Adjust animations for smoother floating effect

feat: Create and style bubbles with centered layout

---

src/styles/Bubbles.module.css

- Update bubble dimensions for improved appearance and spacing
- Resize images within bubbles for optimal fit and visual consistency
- Ensure responsive adjustments for different screen sizes
- Refine CSS styles for better alignment and presentation of content

chore: Adjust bubble and image size for better layout

---

src/App.module.css
src/pages/About.jsx
src/styles/About.module.css

- Expand and enhance the about story content to provide a more detailed and engaging narrative.
- Add a section emphasizing the ability to create messages for future generations.
- Update the styling of the about page for improved readability and visual appeal.
- Ensure responsiveness and consistent formatting across different devices.
- Add emphasis on Memo Bubble's mission and user experience enhancements.

feat: Update About Page Content and Styling

---

src/App.js
src/components/footer/DeveloperDetails.jsx
src/pages/contact/ContactForm.jsx
src/pages/contact/ContactPage.jsx
src/styles/ContactForm.module.css
src/styles/Footer.module.css
src/styles/ServicesPages.module.css

- Add styling for the Contact Page
- Update CSS
- Enhance form elements with new styles
- Improve code
- Update routing to ensure proper navigation to Contact Page
- Include meta tags for SEO optimization

feat: Style Contact Page and Update Code

---

src/pages/legal/FAQ.jsx
src/styles/ContactForm.module.css
src/styles/ServicesPages.module.css

- Implement FAQPage component with a structured layout using React and React-Bootstrap.
- Add an introductory paragraph to provide users with an overview of the FAQ section.
- Include nine frequently asked questions and their corresponding answers.
- Style the page for a clean and user-friendly presentation.

Set up FAQ page with questions and answers

---

src/App.js
src/App.module.css
src/components/footer/DeveloperDetails.jsx
src/components/footer/Footer.jsx
src/pages/capsules/Bubbles.jsx
src/pages/legal/FAQ.jsx
src/pages/legal/Terms.jsx
src/styles/ServicesPages.module.css

- Add initial content for the Terms of Service page
- Fix missing forward slash in App.js links to ensure proper navigation
- Note: Terms of Service content will be fully updated in due time

Set up Terms of Service page and fix links in App.js

---

src/components/BubbleGame.jsx
src/components/footer/LegalLinks.jsx
src/pages/contact/ContactPage.jsx
src/pages/errors/NotFound.jsx
src/pages/legal/PrivacyPolicy.jsx
src/styles/BubbleGame.module.css
src/styles/ServicesPages.module.css

- Implement BubbleGame component with timer, score, and bubble popping mechanics.
- Add game start button and timer display.
- Style bubble game area with floating bubbles animation.
- Update NotFound page to include the bubble game and integrated start button functionality.
- Add CSS styles for game container, bubbles, and timer.
- Note: Game functionality includes a one-minute timer and bubble popping with score tracking.

feat: Add interactive bubble game to 404 page

---

src/components/BubbleGame.jsx
src/pages/errors/Forbidden403.jsx
src/pages/errors/NotFound.jsx

- Adjust style to match the rest of the app

style: Style forbidden 403 page

---

src/App.module.css
src/components/MoreDropDown.js
src/components/footer/DeveloperDetails.jsx
src/components/footer/Footer.jsx
src/pages/profiles/ProfileEditForm.jsx
src/pages/profiles/ProfilePage.jsx
src/styles/Avatar.module.css
src/styles/Button.module.css
src/styles/MoreDropdown.module.css
src/styles/ProfilePage.module.css

- Adjust padding in the footer for improved spacing.
- Add a border to the avatar in the navigation bar for better visibility.
- Enhance the styling of the profile page for a more consistent look and feel.
- Note: Some more styling enhancement needed for profile

style: Adjust footer padding, add border to avatar in nav, and style profile page

---

src/components/Avatar.jsx
src/components/NavBar.jsx
src/pages/profiles/ProfileEditForm.jsx
src/pages/profiles/ProfilePage.jsx
src/pages/profiles/UserPasswordForm.jsx
src/pages/profiles/UsernameForm.jsx
src/styles/MoreDropdown.module.css
src/styles/ProfilePage.module.css

Style Profile page and it's forms

---

src/components/MoreDropDown.js
src/styles/MoreDropdown.module.css

- Implement 'Delete My Profile' option in ProfileEditDropdown.
- Style dropdown menu with updated icons and classes.

Add profile deletion option in dropdown menu

---

src/components/MoreDropDown.js
src/components/UserCapsules.jsx
src/pages/auth/SignInForm.jsx
src/pages/auth/SignUpForm.jsx
src/pages/capsules/Bubbles.jsx
src/pages/capsules/CapsuleCreateForm.jsx
src/pages/profiles/ProfilePage.jsx
src/styles/Button.module.css
src/styles/Home.module.css
src/styles/MoreDropdown.module.css
src/styles/ProfilePage.module.css
src/styles/SignInUpForm.module.css

- Added a 'Back to Profile' button in the card footer to navigate back to the user's profile.
- Replaced the link with a button for the 'Add capsule' action in the card footer.
- Updated the styling and onClick handlers to use history.push for navigation.

Add 'Back to Profile' and 'Add capsule' buttons to UserCapsules component, add custom red to alert warnings for signup/signin pages

---

src/components/Avatar.jsx
src/pages/profiles/ProfilePage.jsx

- Replace local placeholder image with URL from S3 bucket.
- Update Avatar component to fallback to S3 placeholder when no src is provided.

fix: Use S3 placeholder URL for avatar component

---

src/pages/Home.jsx
src/pages/capsules/Bubbles.jsx
src/styles/Bubbles.module.css

feat: Add sorting options and header to bubbles(Memory Sanctuary) page
fix: Correct Home page button to navigate to Bubbles using history.push

feat: Add sorting options to bubbles page, fix: Correct Home page button

---

package-lock.json
package.json
src/components/CapsuleCreateEditForm/CreatEditFormFields.jsx
src/pages/capsules/Bubbles.jsx
src/pages/capsules/CapsuleCreateForm.jsx
src/styles/Bubbles.module.css
src/styles/CapsuleCreateForm.module.css
src/styles/SignInUpForm.module.css

>>
>> - Integrate Google Maps Places API for location autocomplete.
>> - Load Google Maps API script dynamically in CreatEditFormFields component.
>> - Implement autocomplete functionality with location suggestions and selection.
>> - Update handleInputChange to handle location input and fetch suggestions.
-Note: Google Maps API key throwing error. To be checked!

feat: Add Google Places Autocomplete to Capsule Create Form

---

src/components/CapsuleBubble.jsx
src/components/Comments.jsx
src/pages/capsules/Bubbles.jsx
src/styles/BubbleGame.module.css
src/styles/Bubbles.module.css
src/styles/Capsule.module.css
src/styles/CapsuleCreateForm.module.css
src/styles/Comments.module.css
src/styles/MoreDropdown.module.css
src/styles/ProfilePage.module.css
src/styles/SignInUpForm.module.css

- Implement Comments component for adding comments to capsules.
- Integrate Comments into the Capsule page.
- Style Comments section.
- Add error handling for comment submission.
- Note: CSRF token issue pending resolution.

feat: Add Comment Feature to Frontend

---

src/App.js
src/App.module.css
src/components/NavBar.jsx
src/styles/Button.module.css
src/styles/CapsuleCreateForm.module.css
src/styles/ContactForm.module.css
src/styles/NavBar.module.css
src/styles/ProfilePage.module.css
src/styles/SignInUpForm.module.css

- Style the Cookie Consent banner with custom buttons and improved appearance.
- Fix functionality for setting cookie consent values and managing the cookie banner visibility.
- Revise cookie consent message to include Google Places and Gemini.

fix: Fix cookie consent banner functionality and styling

---

src/components/NavBar.jsx
src/components/NotificationBell.jsx
src/styles/NavBar.module.css

- Create NotificationBell component to handle notification icon display based on unseen notifications.
- Integrate NotificationBell into NavBar, displayed conditionally based on user authentication.
- Update CSS styles for NotificationBell and adjusted layout to ensure proper display in NavBar.

feat: Add NotificationBell component and integrate into NavBar
